#ifndef DEF_ICON_FOLDER
#	define DEF_ICON_FOLDER DEF_ICON
#endif

DEF_ICON(NONE)

DEF_ICON(BACK)
DEF_ICON(FORWARD)

DEF_ICON_FOLDER(FILE_FOLDER)
DEF_ICON(FILE_3D)
DEF_ICON(FILE_BLANK)
DEF_ICON(FILE_PARENT)
