#ifndef DRAW_STATE_H
#define DRAW_STATE_H

#include "LIB_utildefines.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum DRWState {
	/** To be used for compute passes. */
	DRW_STATE_NO_DRAW = 0,
	/** Write mask */
	DRW_STATE_WRITE_DEPTH = (1 << 0),
	DRW_STATE_WRITE_COLOR = (1 << 1),
	/* Write Stencil. These options are mutual exclusive and packed into 2 bits */
	DRW_STATE_WRITE_STENCIL = (1 << 2),
	DRW_STATE_WRITE_STENCIL_SHADOW_PASS = (2 << 2),
	DRW_STATE_WRITE_STENCIL_SHADOW_FAIL = (3 << 2),
	/** Depth test. These options are mutual exclusive and packed into 3 bits */
	DRW_STATE_DEPTH_ALWAYS = (1 << 4),
	DRW_STATE_DEPTH_LESS = (2 << 4),
	DRW_STATE_DEPTH_LESS_EQUAL = (3 << 4),
	DRW_STATE_DEPTH_EQUAL = (4 << 4),
	DRW_STATE_DEPTH_GREATER = (5 << 4),
	DRW_STATE_DEPTH_GREATER_EQUAL = (6 << 4),
	/** Culling test */
	DRW_STATE_CULL_BACK = (1 << 7),
	DRW_STATE_CULL_FRONT = (1 << 8),
	/** Stencil test. These options are mutually exclusive and packed into 2 bits. */
	DRW_STATE_STENCIL_ALWAYS = (1 << 9),
	DRW_STATE_STENCIL_EQUAL = (2 << 9),
	DRW_STATE_STENCIL_NEQUAL = (3 << 9),

	/** Blend state. These options are mutual exclusive and packed into 4 bits */
	DRW_STATE_BLEND_ADD = (1 << 11),
	/** Same as additive but let alpha accumulate without pre-multiply. */
	DRW_STATE_BLEND_ADD_FULL = (2 << 11),
	/** Standard alpha blending. */
	DRW_STATE_BLEND_ALPHA = (3 << 11),
	/** Use that if color is already pre-multiply by alpha. */
	DRW_STATE_BLEND_ALPHA_PREMUL = (4 << 11),
	DRW_STATE_BLEND_BACKGROUND = (5 << 11),
	DRW_STATE_BLEND_OIT = (6 << 11),
	DRW_STATE_BLEND_MUL = (7 << 11),
	DRW_STATE_BLEND_SUB = (8 << 11),
} DRWState;

ENUM_OPERATORS(DRWState, DRW_STATE_BLEND_SUB);

#define DRW_STATE_DEFAULT (DRW_STATE_WRITE_DEPTH | DRW_STATE_WRITE_COLOR | DRW_STATE_DEPTH_LESS_EQUAL)
#define DRW_STATE_BLEND_ENABLED (DRW_STATE_BLEND_ADD | DRW_STATE_BLEND_ADD_FULL | DRW_STATE_BLEND_ALPHA | DRW_STATE_BLEND_ALPHA_PREMUL | DRW_STATE_BLEND_BACKGROUND | DRW_STATE_BLEND_OIT | DRW_STATE_BLEND_MUL | DRW_STATE_BLEND_SUB)
#define DRW_STATE_RASTERIZER_ENABLED (DRW_STATE_WRITE_DEPTH | DRW_STATE_WRITE_COLOR | DRW_STATE_WRITE_STENCIL | DRW_STATE_WRITE_STENCIL_SHADOW_PASS | DRW_STATE_WRITE_STENCIL_SHADOW_FAIL)
#define DRW_STATE_DEPTH_TEST_ENABLED (DRW_STATE_DEPTH_ALWAYS | DRW_STATE_DEPTH_LESS | DRW_STATE_DEPTH_LESS_EQUAL | DRW_STATE_DEPTH_EQUAL | DRW_STATE_DEPTH_GREATER | DRW_STATE_DEPTH_GREATER_EQUAL)
#define DRW_STATE_STENCIL_TEST_ENABLED (DRW_STATE_STENCIL_ALWAYS | DRW_STATE_STENCIL_EQUAL | DRW_STATE_STENCIL_NEQUAL)
#define DRW_STATE_WRITE_STENCIL_ENABLED (DRW_STATE_WRITE_STENCIL | DRW_STATE_WRITE_STENCIL_SHADOW_PASS | DRW_STATE_WRITE_STENCIL_SHADOW_FAIL)

#ifdef __cplusplus
}
#endif

#endif
