#pragma once

#include "LIB_sys_types.h"

#ifdef __cplusplus
extern "C" {
#endif

struct ID;
struct Main;

enum {
	IDWALK_RET_NOP = 0,
	/** Competely stop the iteration. */
	IDWALK_RET_STOP_ITER = (1 << 0),
	/** Stop recursion, that is, do not loop over ID used by current one. */
	IDWALK_RET_STOP_RECURSION = (1 << 1),
};

typedef struct LibraryIDLinkCallbackData {
	void *user_data;

	/** Main database used to call `KER_library_foreach_ID_link()`. */
	struct Main *main;
	/** The one that might be in main, only differs from #self_id when the later is not registered in #Main. */
	struct ID *owner_id;
	/** ID from which the current ID pointer is being processed. */
	struct ID *self_id;
	struct ID **id_pointer;

	int cb_flag;
} LibraryIDLinkCallbackData;

/**
 * Call a callback for each ID link which the given ID uses.
 *
 * \return a set of flags to control further iteration (0 to keep going).
 */
typedef int (*LibraryIDLinkCallback)(LibraryIDLinkCallbackData *cb_data);

/** #LibraryIDLinkCallbackData->flag */
enum {
	IDWALK_CB_NOP = 0,
	IDWALK_CB_NEVER_NULL = (1 << 0),
	IDWALK_CB_NEVER_SELF = (1 << 1),

	/**
	 * Indicates that this is an internal runtime ID pointer, like e.g. #ID->new_id or #ID->old_id.
	 * \note Those should be ignored in most cases, and won't be processed/generated anyway unless
	 * `IDWALK_DO_INTERNAL_RUNTIME_POINTERS` is specified.
	 */
	IDWALK_CB_INTERNAL = (1 << 9),
	/** This ID usage is fully refcounted, callback is responsible to deal accordinglu with #ID->us if neeeded. */
	IDWALK_CB_USER = (1 << 10),
	/** This ID usage is not refcounted, but at least one user should be generated by it. */
	IDWALK_CB_USER_ONE = (1 << 11),
};

typedef struct LibraryForeachIDData LibraryForeachIDData;

enum {
	IDWALK_NOP = 0,
	/**
	 * The callback will never modify the ID pointers it processes.
	 * WARNING: It is very important to pass this flag when valid, as it can lead to important
	 * optimizations and debug/assert code.
	 */
	IDWALK_READONLY = (1 << 0),
	/**
	 * Recurse into `descendant` IDs.
	 * Each ID is only processed once, order of ID processing is not guaranteed.
	 *
	 * Also implies IDWALK_READONLY, and excludes IDWALK_DO_INTERNAL_RUNTIME_POINTERS.
	 */
	IDWALK_RECURSE = (1 << 1),
	/**
	 * Include UI pointers (from WM and screen editors).
	 */
	IDWALK_INCLUDE_UI = (1 << 2),
	/**
	 * Do not access the original processed pointer's data, only process its address value.
	 *
	 * This is required in cases where the current address may not be valid anymore.
	 */
	IDWALK_NO_ORIG_POINTERS_ACCESS = (1 << 3),
	IDWALK_DO_INTERNAL_RUNTIME_POINTERS = (1 << 4),

	/**
	 * Also process the #ID->lib pointer. It is an option because this pointer can usually be full ignored.
	 */
	IDWALK_DO_LIBRARY_POINTER = (1 << 5),
};

bool KER_lib_query_foreachid_iter_stop(const struct LibraryForeachIDData *data);
void KER_lib_query_foreachid_process(struct LibraryForeachIDData *data, struct ID **id_pp, int flag);

int KER_lib_query_foreachid_process_flags_get(LibraryForeachIDData *data);
int KER_lib_query_foreachid_process_callback_flag_override(LibraryForeachIDData *data, int flag, bool replace);

/* clang format off */

#define KER_LIB_FOREACHID_PROCESS_ID_NOCHECK(data_, id_, cb_flag_) \
	{ \
		KER_lib_query_foreachid_process((data_), (ID **)&(id_), (cb_flag_)); \
		if (KER_lib_query_foreachid_iter_stop((data_))) { \
			return; \
		} \
	} \
	((void)0)

#define KER_LIB_FOREACHID_PROCESS_ID(data_, id_, cb_flag_) \
	{ \
		KER_LIB_FOREACHID_PROCESS_ID_NOCHECK(data_, id_, cb_flag_); \
	} \
	((void)0)

#define KER_LIB_FOREACHID_PROCESS_IDSUPER_P(data_, id_super_p_, cb_flag_) \
	{ \
		KER_lib_query_foreachid_process((data_), (ID **)(id_super_p_), (cb_flag_)); \
		if (KER_lib_query_foreachid_iter_stop((data_))) { \
			return; \
		} \
	} \
	((void)0)

#define KER_LIB_FOREACHID_PROCESS_IDSUPER(data_, id_super_, cb_flag_) \
	{ \
		KER_LIB_FOREACHID_PROCESS_IDSUPER_P(data_, &(id_super_), cb_flag_); \
	} \
	((void)0)

#define KER_LIB_FOREACHID_PROCESS_FUNCTION_CALL(data_, func_call_) \
	{ \
		func_call_; \
		if (KER_lib_query_foreachid_iter_stop((data_))) { \
			return; \
		} \
	} \
	((void)0)

/* clang format on */

void KER_library_foreach_ID_link(struct Main *main, struct ID *id, LibraryIDLinkCallback cb, void *user_data, int flag);

/**
 * Say whether given \a owner_id may use (in any way) a data-block of \a id_type.
 *
 * This is used to achieve many optimizations when searching for specific #ID inside another data-block.
 */
bool KER_library_id_can_use_idtype(struct ID *owner_id, short id_type);

#ifdef __cplusplus
}
#endif
