#pragma once

#define ROSE_VERSION_MAJOR	0
#define ROSE_VERSION_MINOR	3
#define ROSE_VERSION_REVISION	1
#define ROSE_VERSION_STATUS	"-dev"

#define ROSEAUX_STR_EXP(__A)	#__A
#define ROSEAUX_STR(__A)	ROSEAUX_STR_EXP(__A)

#define ROSEAUX_STRW_EXP(__A)	L ## #__A
#define ROSEAUX_STRW(__A)	ROSEAUX_STRW_EXP(__A)

#define ROSE_VERSION		ROSEAUX_STR(ROSE_VERSION_MAJOR) "." ROSEAUX_STR(ROSE_VERSION_MINOR) "." ROSEAUX_STR(ROSE_VERSION_REVISION) ROSE_VERSION_STATUS

#define ROSE_MAJOR_VERSION	ROSE_VERSION_MAJOR
#define ROSE_MINOR_VERSION	ROSE_VERSION_MINOR
#define ROSE_SUBMINOR_VERSION	ROSE_VERSION_REVISION
