#pragma once

#include "DNA_sdna_types.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * DNAstr contains the prebuilt SDNA structure defining the layouts of the types
 * used by this version of Blender. It is defined in a file dna.c, which is
 * generated by the `makesdna` program during the build process (see `makesdna.cc`).
 */
extern const unsigned char DNAstr[];
/** Length of DNAstr. */
extern const int DNAlen;

struct SDNA *DNA_sdna_from_data(const void *data, int data_len, bool data_alloc, const char **r_error_message);

void DNA_sdna_current_init(void);
void DNA_sdna_current_free(void);

const struct SDNA *DNA_sdna_current_get(void);

#ifdef __cplusplus
}
#endif
