#pragma once

#if defined(__cplusplus)
extern "C" {
#endif

enum {
	GPU_INFO_MAX_TEXTURE_SIZE,
	GPU_INFO_MAX_TEXTURE_3D_SIZE,
	GPU_INFO_MAX_TEXTURE_LAYERS,
	GPU_INFO_MAX_TEXTURES,
	GPU_INFO_MAX_TEXTURES_VERT,
	GPU_INFO_MAX_TEXTURES_GEOM,
	GPU_INFO_MAX_TEXTURES_FRAG,
	GPU_INFO_MAX_SAMPLERS,
	GPU_INFO_MAX_WORK_GROUP_COUNT_X,
	GPU_INFO_MAX_WORK_GROUP_COUNT_Y,
	GPU_INFO_MAX_WORK_GROUP_COUNT_Z,
	GPU_INFO_MAX_WORK_GROUP_SIZE_X,
	GPU_INFO_MAX_WORK_GROUP_SIZE_Y,
	GPU_INFO_MAX_WORK_GROUP_SIZE_Z,
	GPU_INFO_MAX_UNIFORMS_VERT,
	GPU_INFO_MAX_UNIFORMS_FRAG,
	GPU_INFO_MAX_BATCH_INDICES,
	GPU_INFO_MAX_BATCH_VERTICES,
	GPU_INFO_MAX_VERTEX_ATTRIBS,
	GPU_INFO_MAX_VARYING_FLOATS,
	GPU_INFO_MAX_STORAGE_BUFFER_SIZE,
	GPU_INFO_MAX_SHADER_STORAGE_BUFFER_BINDINGS,
	GPU_INFO_MAX_COMPUTE_SHADER_STORAGE_BLOCKS,
	GPU_INFO_EXTENSIONS_LEN,

	GPU_INFO_MEM_STATS_SUPPORT,
	GPU_INFO_COMPUTE_SHADER_SUPPORT,
	GPU_INFO_GEOMETRY_SHADER_SUPPORT,
	GPU_INFO_SHADER_STORAGE_BUFFER_OBJECTS_SUPPORT,
	GPU_INFO_SHADER_IMAGE_LOAD_STORE_SUPPORT,
	GPU_INFO_SHADER_DRAW_PARAMETERS_SUPPORT,
	GPU_INFO_TRANSFORM_FEEDBACK_SUPPORT,

	GPU_INFO_MIP_RENDER_WORKAROUND,
	GPU_INFO_DEPTH_BLITTING_WORKAROUND,
	GPU_INFO_USE_MAIN_CONTEXT_WORKAROUND,
	GPU_INFO_BROKEN_AMD_DRIVER,
	GPU_INFO_USE_HQ_NORMALS_WORKAROUND,
	GPU_INFO_CLEAR_VIEWPORT_WORKAROUND,

	GPU_INFO_MINIMUM_PER_VERTEX_STRIDE,
	GPU_INFO_LEN,
};

int GPU_get_info_i(int info);
float GPU_get_info_f(int info);

#if defined(__cplusplus)
}
#endif
